create sequence category_seq start with 1 increment by 1;
create sequence country_seq start with 1 increment by 1;
create sequence game_seq start with 1 increment by 1;
create sequence message_seq start with 1 increment by 1;
create sequence message_to_support_seq start with 1 increment by 1;
create sequence offer_seq start with 1 increment by 1;
create sequence review_seq start with 1 increment by 1;
create sequence transaction_seq start with 1 increment by 1;
create sequence user_blocking_seq start with 1 increment by 1;
create sequence users_seq start with 1 increment by 1;
create sequence vip_status_seq start with 1 increment by 1;
create table category (id bigint not null, name varchar(255) not null, primary key (id));
create table country (id bigint not null, name varchar(255) not null, primary key (id));
create table game (id bigint not null, name varchar(255) not null, path_to_poster varchar(255), primary key (id));
create table message (id bigint not null, message_date date not null, receiver_id bigint, sender_id bigint, message_subject varchar(255) not null, text varchar(255) not null, primary key (id));
create table message_to_support (id bigint not null, message_date date not null, sender_id bigint, message_subject varchar(255) not null, text varchar(255) not null, primary key (id));
create table offer (category_id bigint, creation_date date not null, game_id bigint, id bigint not null, price_per_lot bigint not null, quantity_goods_in_lot bigint not null, seller_id bigint, vip_status_id bigint unique, description varchar(255) not null, name varchar(255) not null, obtain_method varchar(255) not null, primary key (id));
create table review (moderation_check_status smallint not null check (moderation_check_status between 0 and 1), rating smallint not null, buyer_id bigint, dispatch_time date not null, id bigint not null, seller_id bigint, game_name varchar(255) not null, text varchar(255), primary key (id));
create table transaction (buyer_status smallint not null check (buyer_status between 0 and 2), seller_status smallint not null check (seller_status between 0 and 2), buyer_id bigint, id bigint not null, offer_id bigint, price_per_lot bigint not null, quantity_goods bigint not null, seller_id bigint, primary key (id));
create table user_blocking (expiration_date date not null, id bigint not null, user_id bigint, reason varchar(255), primary key (id));
create table users (account_status varchar(255) not null check (account_status in ('ADMIN', 'USER')), user_status smallint not null check (user_status between 0 and 1), balance bigint, country_id bigint, id bigint not null, last_login_date date, registration_date date not null, email varchar(255), login varchar(255) not null, password varchar(255) not null, path_to_avatar varchar(255), username varchar(255) not null, code int, primary key (id));
create table vip_status (expiration_date_vip_status date not null, id bigint not null, primary key (id));
create index IDX46ccwnsi9409t36lurvtyljak on category (name);
create index IDXllidyp77h6xkeokpbmoy710d4 on country (name);
create index IDXjare70vqqti665ds3b2eh7rk8 on game (name);
alter table if exists message add constraint FK9a25x9o5r7wguarxeon2a9tmr foreign key (receiver_id) references users;
alter table if exists message add constraint FKbi5avhe69aol2mb1lnm6r4o2p foreign key (sender_id) references users;
alter table if exists message_to_support add constraint FKsjfag3y3eym2bf91c2ndrqcmc foreign key (sender_id) references users;
alter table if exists offer add constraint FKkaaxymqfu6ccvk2rppoc1xy0x foreign key (category_id) references category;
alter table if exists offer add constraint FKaay6asfipnou4s9q4ge305o0o foreign key (game_id) references game;
alter table if exists offer add constraint FKf4v1a6i0o2soe5syorhsracou foreign key (seller_id) references users;
alter table if exists offer add constraint FKr7chnkh6imqp9244q47dhyjyl foreign key (vip_status_id) references vip_status;
alter table if exists review add constraint FK3e8apdjtpgmexobcbpbximbb6 foreign key (buyer_id) references users;
alter table if exists review add constraint FK6kh0e088y90t0mga5rbfvqfdi foreign key (seller_id) references users;
alter table if exists transaction add constraint FKlri5uh1w3mea6fdu8ho7ccq5m foreign key (buyer_id) references users;
alter table if exists transaction add constraint FK7gjuaeg7oa6o0eixgpxp4sarr foreign key (offer_id) references offer;
alter table if exists transaction add constraint FKr9xwpmvtk2y214bdbgbi8n749 foreign key (seller_id) references users;
alter table if exists user_blocking add constraint FK9y5mp8hi8y6nu0tdqibxxwddy foreign key (user_id) references users;
alter table if exists users add constraint FK5t4yyo3f0ctxayh7voqv51fmg foreign key (country_id) references country;
